# Generated by Django 4.2.23 on 2025-08-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('description', models.TextField()),
            ],
        ),
    ]
